################
#   Database   #
################

[database]
username = "pocockn"
password = "pocockn"
host = "127.0.0.1"
databaseName = "docker_pocockn"
port = "3306"

[s3]
domain = "http://s3.local.shouts.co.uk:4569"
bucket = "image-analysis-shouts"